### ISSUE TITLE
Release on Modrinth

### ISSUE THREAD

**Issue by intergrav** [hammy3502/immersive-mc#101]
[Modrinth](https://modrinth.com/) is a great site and I think ImmersiveMC would be nice to have on there considering Vivecraft is now available there. I don't mean to completely move over - but have both CurseForge and Modrinth pages maintained.

**Comment by hammy275** [comment]
I've honestly been thinking about publishing on Modrinth, and will hopefully do so soon:tm:. The main issue is that I already publish on two places (CurseForge and GitHub), so it'd be a bit of extra work, but it would be a good idea for people using PolyMC or similar, since CurseForge modpacks in third-party launchers aren't really a thing anymore

**Comment by intergrav** [comment]
Sounds good!

**Comment by hammy275** [comment]
Done!
