### ISSUE TITLE
Chest Instantly Closes After Opening

### ISSUE THREAD

**Issue by hammy275** [hammy3502/immersive-mc#118]
Mixins (probably), please

**Comment by hammy275** [comment]
Might also be the chest not respecting the open/close cooldown, since the report came from someone in VR

**Comment by hammy275** [comment]
Bug report is from a user on CurseForge, but I can't actually reproduce this. Will leave open for now, but might close at some point.

**Comment by soup587** [comment]
seems to occur on 1.18.2 fabric, i was playing with other mods at the time so i'll get a list when i can

**Comment by hammy275** [comment]
Have received several reports, this is definitely happening. Need to track down what's going on with this

**Comment by hammy275** [comment]
Closing, as this is now a duplicate of #143 . Moving to there since that issue better describes what's happening

**Comment by BrianNormant** [comment]
Hello, i don't know if i should open a new ticket because my issue is exactly the same as the title ticket.

As I said, chest close instantly after opening. After some digging it seem to be caused by the mod things (https://www.curseforge.com/minecraft/mc-mods/things-fabric)

Mod used (according to curseforge):
Architectury API
Cloth Config API
Fabric API
Forge Config Port
ImmersiveMC
ModMenu
owo (owo-lib)
Patchouli
Things [Fabric]
Trinkets.

The issue only happen with things installed, althought the chest close instantly everything is functionnal (i can add/grab and cycle). I believe the issue is caused by a Things feature that allow you to lock chest. 
Using AMD 6900xt and Ryzen R7 5800X, if that matter
