### ISSUE TITLE
не работает с модом Create

### ISSUE THREAD

**Issue by Hranitel** [hammy3502/immersive-mc#141]
with the Create mod, the game resets all resource packs and then just crashes

**Comment by hammy275** [comment]
What version of Minecraft are you using, and which modloader are you using? Can you also send a crash log so I can see what may be happening?

**Comment by Hranitel** [comment]
1,19,2
forge
[tl-logger11339887621182878672.txt](https://github.com/hammy3502/immersive-mc/files/10269764/tl-logger11339887621182878672.txt)

**Comment by hammy275** [comment]
Hi, I was able to track down this issue. Please either uninstall Optifine or the Create mod, as they don't seem to be compatible with each other.

This doesn't seem to do with ImmersiveMC, so I'm closing the issue

**Comment by Hranitel** [comment]
the fact is that everything works without ImmersiveMC.
I added it to my VR build and it stopped running.

**Comment by hammy275** [comment]
I can only reproduce this issue with your list of mods using Create and Optifine with no other mods. Can you verify the game running with both Create and Optifine at the same time?

**Comment by Hranitel** [comment]
but can Vivecraft work without Optifine?

**Comment by hammy275** [comment]
You can use the Mixin version of Vivecraft (https://www.curseforge.com/minecraft/mc-mods/vivecraft). It acts like any other mod, but is still Vivecraft otherwise. From there, if you need more performance, use Sodium (or its Forge equivalent) instead of Optifine, and Iris/Oculus if you want shaders (which, unlike Optifine's, do work in ImmersiveMC!)
