### ISSUE TITLE
MedievalWeapons Mod Incompatability

### ISSUE THREAD

**Issue by hammy275** [hammy3502/immersive-mc#143]
Chests immediately close after opening when MedievalWeapons mod is installed.

**Comment by hammy275** [comment]
Since it might be a mixin issue with Architectury, I'll try to remove mixins one by one from MedievalMC. If the issue stops occuring, I can single out the mixin in question, and go from there

**Comment by hammy275** [comment]
I've verified that this isn't an issue with any of the mixins, sadly

**Comment by hammy275** [comment]
No idea why this is happening. Will leave open, but I don't expect to find anything anytime soon. If anyone has any ideas, I'm all ears.

**Comment by BrianNormant** [comment]
Using Fabric 1.19.2

Same as when title say but with Things mod installed

As I said, chest close instantly after opening. After some digging it seem to be caused by the mod things (https://www.curseforge.com/minecraft/mc-mods/things-fabric)

Mod used (according to curseforge):
Architectury API
Cloth Config API
Fabric API
Forge Config Port
ImmersiveMC
ModMenu
owo (owo-lib)
Patchouli
Things [Fabric]
Trinkets.

The issue only happen with things installed, althought the chest close instantly everything is functionnal (i can add/grab and cycle). I believe the issue is caused by a Things feature that allow you to lock chest.
Using AMD 6900xt and Ryzen R7 5800X, if that matter

**Comment by BrianNormant** [comment]
It Also do the same thing with MC Dungeons Weapons https://www.curseforge.com/minecraft/mc-mods/mcdw

**Comment by hammy275** [comment]
Thank you so much for the reports! I'll have to figure out what it is with these three mods that break things.

**Comment by hammy275** [comment]
A gut feeling: A config desync that occurs when a mod leveraging cloth config is installed? Seems weird, but it's worth a go to check. Use debugging on threads to make sure config stuff is being synced properly. Also see if the mixin change is still being applied properly

**Comment by hammy275** [comment]
I finally found the problem. Some mods use custom ranges for interacting with chests using this library: https://github.com/JamiesWhiteShirt/reach-entity-attributes . This mixin: https://github.com/JamiesWhiteShirt/reach-entity-attributes/blob/1.19/src/main/java/com/jamieswhiteshirt/reachentityattributes/mixin/ChestStateManagerMixin.java mixes into the exact spot before we do, redirecting execution to its own function, preventing us from running!

Solution is to look into mixin documentation to figure out how to stack our value on top of this.

**Comment by hammy275** [comment]
Will ModifyVariable into `i` for the function that calls `getOpenCount`

**Comment by hammy275** [comment]
This is finally fixed and will be released with version 1.2.0. Thank you so much for the help :)

**Comment by BrianNormant** [comment]
I'm really happy to have helped. Any date you think you'll release v 1.2.0?

**Comment by hammy275** [comment]
I'm hoping to get it out within a week or two, but no guarantees on when. If you're familiar with compiling, feel free to compile the `1.19.x` branch or `1.18.x-multiloader` branch

**Comment by BrianNormant** [comment]
ok thanks, loving your mod btw
