### ISSUE TITLE
Immersive Quiver [VR Only]

### ISSUE THREAD

**Issue by RedRain0o0** [hammy3502/immersive-mc#182]
When there is a bow in your hand, a little Quiver appears on your hip(L/R depending on hand holding bow)
You just reach to the Quiver with your free hand and grip to grab

**Comment by hammy275** [comment]
I don't think it would make sense to do this one, since Vivecraft will automatically have you hold an arrow when you switch to your bow. This would probably be a better suggestion on their end, but since quivers aren't really in the game, I don't think they'd add it.

Sorry, but thank you for the suggestion! If you have any others, I'd still absolutely want to hear them :)
