### ISSUE TITLE
Bug: Game crashes with 'impaled' mod

### ISSUE THREAD

**Issue by Fazzoc** [hammy3502/immersive-mc#233]
https://mclo.gs/4f8BwjT
i made sure to checked what caused it.
it crashes on startup.

**Comment by hammy275** [comment]
Thanks for the bug report! From what I understand, the place that ImmersiveMC redirects code to allow for immersively throwing Tridents and the place where Impaled works with handling Sincere Loyalty are the same, so there's a conflict since we're both trying to change code in the same spot.

For myself:

The Mixin conflict is with this file: https://github.com/Ladysnake/Impaled/blob/1.18/src/main/java/ladysnake/sincereloyalty/mixin/TridentItemMixin.java up against the throw redirector for the Trident. Both their Mixin and mine are super reasonable.

Looks like Mixin has a priority system (https://github.com/PaceCodes/Mixin-Tutorial/blob/master/Cheatsheet/mixin-priority.md is a nice, basic resource I found on it). We're both effectively defaulting to 1000 at the moment, which would cause issues. I wonder if I bump mine up to come after Impaled if things would be good. They should definitely go first before me, and mine is more "drastic" (a code redirection).
