### ISSUE TITLE
Bag doesnt work in VR

### ISSUE THREAD

**Issue by Justmoonboy** [hammy3502/immersive-mc#240]
I added open/close bag to my radial menu but when I click it the bag doesn't open

**Comment by hammy275** [comment]
Make sure you have mc-vr-api installed for the same Minecraft version and modloader as what you're playing.

Also, if you're playing on ImmersiveMC 1.3.0 or later, make sure you have mc-vr-api 3.0.0 or later. If you're playing before ImmersiveMC 1.3.0, make sure you're using mc-vr-api BEFORE 3.0.0.

Closing, since support is provided on the Discord, not in GitHub. Please go there if you need help.
