### ISSUE TITLE
vanilla Interactions disabled for barrels

### ISSUE THREAD

**Issue by TheNukeLore** [hammy3502/immersive-mc#341]
as mentioned in the title. vanilla interaction for barrels is disabled no matter what you set the config option to (Disable Vanilla Interactions) this disallows opening barrels in the base game and requires use of the blue boxes, which cant be accessed from the sides.

**Comment by hammy275** [comment]
This is intentional. You can access the vanilla barrel by sneak+right-clicking or disabling the barrel immersive entirely. If neither of these work, please let me know and I can re-open this issue (or submit it as a new one).

If you have any suggestions on how to allow vanilla interactions with the barrel while keeping the ImmersiveMC one as well, please let me know :)

**Comment by TheNukeLore** [comment]
Why does this only affect the barrel ui? Chest crafting table brewing stand etc. all still allow the vanilla ui, but the barrel is the only one that doesn’t allow it.

**Comment by hammy275** [comment]
There isn't another good way for non-VR users to access the immersive functions that I can think of, in the same way where "Right Click Chests" is required to be enabled for the chest as it prevents the vanilla chest UI.

I realize that I'm assuming you aren't in VR. Are you in VR? If so, I can re-open this, as it doesn't make sense to block right clicks when you can use the hand gesture to open the barrel instead.

**Comment by TheNukeLore** [comment]
I’m specifically wondering why it only affects barrels while literally every single other blocks vanilla ui is accessible. I’m in non vr mode right now

**Comment by hammy275** [comment]
Every other block has some method of avoiding ImmersiveMC's interactions. The side of a crafting table or the space between boxes, the top of a furnace, etc.

The barrel currently has none of those, since the barrel needs to be opened. When implementing the barrel, I programmed opening the barrel to be "right clicking the barrel", since I couldn't think of a better thing to do at the time. As a result, there's no room to put the non-ImmersiveMC interaction, since the entire barrel is already used for ImmersiveMC's interactions.

**Comment by TheNukeLore** [comment]
Could you have simply used the side of the barrel for opening? Because as of right now the barrel is non usable in many ways unless specificly the top is available

**Comment by TheNukeLore** [comment]
Or maybe some sort of vr toggle atleast so the whole mod can be turned off when not using vr

**Comment by hammy275** [comment]
Side of the barrel is a good call (will re-open this issue to implement that).

The toggle is currently planned. Until then, you can disable the barrel on its own if wanted, or just all the immersives

**Comment by hammy275** [comment]
The barrel opening the vanilla UI when right-clicked from the side is added, and will show up in the next ImmersiveMC release
