### ISSUE TITLE
[Forge 1.20.1] Crash upon trying to do the grabbity-grab thing

### ISSUE THREAD

**Issue by Spenz0r** [hammy3502/immersive-mc#393]
On Valve Index, latest Vivecraft version, Embeddium etc.

[crash-2024-04-18_19.25.29-server.txt](https://github.com/hammy275/immersive-mc/files/15031916/crash-2024-04-18_19.25.29-server.txt)

**Comment by hammy275** [comment]
Thanks for the report! I'll look into this and get this fixed! :)

**Comment by hammy275** [comment]
Note to self to patch this:

https://github.com/hammy275/immersive-mc/blob/1.20.4/common/src/main/java/com/hammy275/immersivemc/server/tracker/RangedGrabTrackerServer.java#L46 uses the provided player to the function call, but the tracker system I wrote is stupid, because that player is `null`. Use the player in the info instead lol.

**Comment by hammy275** [comment]
Thanks again for reporting this! The fix should be out with ImmersiveMC 1.5.0 Alpha 3, which will come soon after Minecraft 1.20.5 releases.

**Comment by Spenz0r** [comment]
You're very welcome! You're doing wonders with this mod.
