### ISSUE TITLE
Loading Alongside Forge Mods with Modded Liquids Consistently Causes Crashes 

### ISSUE THREAD

**Issue by DannyDevito747** [hammy3502/immersive-mc#475]
[crash-2024-09-22_06.09.07-client.txt](https://github.com/user-attachments/files/17089155/crash-2024-09-22_06.09.07-client.txt)
Game Version 1.20.1
Crash occurs when any fluid containing item loads in creative menu/inventory.
Tried with multiple forge versions and fresh installs. z
For testing, Mekanism and Immersive MC were only two mods loaded.

**Comment by hammy275** [comment]
Thanks for this report!

**Comment by hammy275** [comment]
Have confirmed this (though I honestly had in the past in development, but thought it wasn't ImmersiveMC-related).

As a note to myself, this was introduced at some point during beta 2's development. Perhaps some Mixin isn't playing nicely with Forge?

**Comment by SHXRKIEgg** [comment]
Same crash happening here with Immersive Engineering
Happens when clicking on the IE creative tab, removing the mod doesnt make it crash (Possible issues with items too that I havent checked)
[crash-2024-10-16_13.33.21-client.txt](https://github.com/user-attachments/files/17389713/crash-2024-10-16_13.33.21-client.txt)

**Comment by hammy275** [comment]
Figured out the issue! Who would've thought mixing in a method named `getFluid()` into `BucketItem` would have zero consequences /s.

Fixing this should be fixed by #478, though to fix this issue specifically, renaming `BucketItemAccessor`'s `getFluid()` method to something else (`immersiveMC$getFluid()` to do the right thing here) will fix this.

**Comment by hammy275** [comment]
This is now fixed, and will be in the next ImmersiveMC release!
